import { User } from "@/lib/types";

// Mock data for student solvers
export const mockSolvers: User[] = [
  {
    id: "solver-1",
    email: "alex.johnson@university.edu",
    name: "Alex Johnson",
    role: "student",
    avatarUrl: "https://i.pravatar.cc/150?u=solver1",
    university: "Stanford University",
    major: "Computer Science",
    graduationYear: "2024",
    experienceLevel: "intermediate",
    skills: ["React", "TypeScript", "Node.js", "UX Research"],
    bio: "I'm a CS major passionate about building user-friendly web applications. I have experience working on several projects using React and TypeScript.",
    languages: ["English", "Spanish"],
    areasOfInterest: ["Web Development", "AI", "Product Design"],
    location: "San Francisco, CA",
    githubUrl: "https://github.com/alexj",
    linkedinUrl: "https://linkedin.com/in/alexjohnson",
    portfolioUrl: "https://alexjohnson.dev",
  },
  {
    id: "solver-2",
    email: "priya.patel@university.edu",
    name: "Priya Patel",
    role: "student",
    avatarUrl: "https://i.pravatar.cc/150?u=solver2",
    university: "MIT",
    major: "Electrical Engineering & Computer Science",
    graduationYear: "2023",
    experienceLevel: "advanced",
    skills: ["Python", "Machine Learning", "Data Analysis", "TensorFlow", "PyTorch"],
    bio: "Machine learning enthusiast with experience in computer vision and NLP. I've completed internships at tech companies and contributed to open-source ML projects.",
    languages: ["English", "Hindi", "Gujarati"],
    areasOfInterest: ["AI/ML", "Computer Vision", "Natural Language Processing"],
    location: "Cambridge, MA",
    githubUrl: "https://github.com/priyap",
    linkedinUrl: "https://linkedin.com/in/priyapatel",
  },
  {
    id: "solver-3",
    email: "marcus.williams@university.edu",
    name: "Marcus Williams",
    role: "student",
    avatarUrl: "https://i.pravatar.cc/150?u=solver3",
    university: "UC Berkeley",
    major: "Business Administration & Computer Science",
    graduationYear: "2025",
    experienceLevel: "beginner",
    skills: ["UI/UX Design", "Figma", "HTML/CSS", "JavaScript"],
    bio: "Studying business and CS with a focus on product design. I'm passionate about creating intuitive and beautiful interfaces that solve real problems.",
    languages: ["English"],
    areasOfInterest: ["Product Design", "Entrepreneurship", "Web Development"],
    location: "Berkeley, CA",
    githubUrl: "https://github.com/marcusw",
    linkedinUrl: "https://linkedin.com/in/marcuswilliams",
    portfolioUrl: "https://marcuswilliams.design",
  },
  {
    id: "solver-4",
    email: "sofia.rodriguez@university.edu",
    name: "Sofia Rodriguez",
    role: "student",
    avatarUrl: "https://i.pravatar.cc/150?u=solver4",
    university: "Georgia Tech",
    major: "Computer Engineering",
    graduationYear: "2024",
    experienceLevel: "intermediate",
    skills: ["Embedded Systems", "C++", "IoT", "PCB Design", "Arduino"],
    bio: "Computer engineering student specializing in IoT and embedded systems. I enjoy building hardware projects and programming microcontrollers.",
    languages: ["English", "Spanish"],
    areasOfInterest: ["IoT", "Robotics", "Smart Home Technology"],
    location: "Atlanta, GA",
    githubUrl: "https://github.com/sofiar",
    linkedinUrl: "https://linkedin.com/in/sofiarodriguez",
  },
  {
    id: "solver-5",
    email: "james.kim@university.edu",
    name: "James Kim",
    role: "student",
    avatarUrl: "https://i.pravatar.cc/150?u=solver5",
    university: "University of Washington",
    major: "Data Science",
    graduationYear: "2023",
    experienceLevel: "advanced",
    skills: ["Data Analysis", "Python", "R", "SQL", "Tableau", "Power BI"],
    bio: "Data science student with strong analytical skills. I've worked on several projects involving large datasets and complex statistical analysis.",
    languages: ["English", "Korean"],
    areasOfInterest: ["Data Visualization", "Business Intelligence", "Big Data"],
    location: "Seattle, WA",
    githubUrl: "https://github.com/jamesk",
    linkedinUrl: "https://linkedin.com/in/jameskim",
  },
  {
    id: "solver-6",
    email: "zoe.chen@university.edu",
    name: "Zoe Chen",
    role: "student",
    avatarUrl: "https://i.pravatar.cc/150?u=solver6",
    university: "Carnegie Mellon University",
    major: "Human-Computer Interaction",
    graduationYear: "2024",
    experienceLevel: "intermediate",
    skills: ["UX Research", "User Testing", "Wireframing", "Prototyping", "Figma"],
    bio: "HCI student focused on creating intuitive user experiences. I believe in user-centered design and validating assumptions through research and testing.",
    languages: ["English", "Mandarin"],
    areasOfInterest: ["UX Design", "Accessibility", "Mobile App Design"],
    location: "Pittsburgh, PA",
    githubUrl: "https://github.com/zoec",
    linkedinUrl: "https://linkedin.com/in/zoechen",
    portfolioUrl: "https://zoechen.design",
  },
  {
    id: "solver-7",
    email: "david.nguyen@university.edu",
    name: "David Nguyen",
    role: "student",
    avatarUrl: "https://i.pravatar.cc/150?u=solver7",
    university: "UCLA",
    major: "Computer Science",
    graduationYear: "2025",
    experienceLevel: "intermediate",
    skills: ["React Native", "Mobile Development", "JavaScript", "Firebase"],
    bio: "CS student specializing in mobile app development. I've created several apps available on the App Store and Google Play.",
    languages: ["English", "Vietnamese"],
    areasOfInterest: ["Mobile App Development", "Cross-platform Solutions", "UX Design"],
    location: "Los Angeles, CA",
    githubUrl: "https://github.com/davidn",
    linkedinUrl: "https://linkedin.com/in/davidnguyen",
    portfolioUrl: "https://davidnguyen.dev",
  },
  {
    id: "solver-8",
    email: "olivia.smith@university.edu",
    name: "Olivia Smith",
    role: "student",
    avatarUrl: "https://i.pravatar.cc/150?u=solver8",
    university: "NYU",
    major: "Interactive Media Arts",
    graduationYear: "2023",
    experienceLevel: "beginner",
    skills: ["UI Design", "Motion Graphics", "Adobe Creative Suite", "HTML/CSS"],
    bio: "Studying interactive media with a focus on digital experiences. I'm passionate about blending technology and art to create engaging user interfaces.",
    languages: ["English"],
    areasOfInterest: ["Interactive Design", "Motion UI", "Web Animation"],
    location: "New York, NY",
    githubUrl: "https://github.com/olivias",
    linkedinUrl: "https://linkedin.com/in/oliviasmith",
    portfolioUrl: "https://oliviasmith.design",
  },
  {
    id: "solver-9",
    email: "ethan.davis@university.edu",
    name: "Ethan Davis",
    role: "student",
    avatarUrl: "https://i.pravatar.cc/150?u=solver9",
    university: "University of Texas at Austin",
    major: "Computer Science",
    graduationYear: "2024",
    experienceLevel: "intermediate",
    skills: ["Golang", "Rust", "System Design", "Microservices", "Docker"],
    bio: "CS student focused on backend development and systems programming. I enjoy building efficient and scalable services.",
    languages: ["English"],
    areasOfInterest: ["Backend Development", "Distributed Systems", "Cloud Computing"],
    location: "Austin, TX",
    githubUrl: "https://github.com/ethand",
    linkedinUrl: "https://linkedin.com/in/ethandavis",
  },
  {
    id: "solver-10",
    email: "maya.patel@university.edu",
    name: "Maya Patel",
    role: "student",
    avatarUrl: "https://i.pravatar.cc/150?u=solver10",
    university: "Brown University",
    major: "Applied Mathematics & Computer Science",
    graduationYear: "2023",
    experienceLevel: "advanced",
    skills: ["Algorithm Design", "Competitive Programming", "Python", "C++"],
    bio: "I'm passionate about solving complex algorithmic problems. I've participated in multiple programming competitions and hackathons.",
    languages: ["English", "Gujarati"],
    areasOfInterest: ["Algorithms", "Competitive Programming", "Software Engineering"],
    location: "Providence, RI",
    githubUrl: "https://github.com/mayap",
    linkedinUrl: "https://linkedin.com/in/mayapatel",
  }
];

export default mockSolvers; 