import { User, Problem } from "@/lib/types";

// Mock data for student solvers
export const mockSolvers: User[] = [
  {
    id: "solver-1",
    email: "alex.johnson@university.edu",
    name: "Alex Johnson",
    role: "student",
    avatarUrl: "https://i.pravatar.cc/150?u=solver1",
    university: "Stanford University",
    major: "Computer Science",
    graduation_year: "2024",
    experience_level: "intermediate",
    skills: ["React", "TypeScript", "Node.js", "UX Research"],
    bio: "I'm a CS major passionate about building user-friendly web applications. I have experience working on several projects using React and TypeScript.",
    languages: ["English", "Spanish"],
    areas_of_interest: ["Web Development", "AI", "Product Design"],
    location: "San Francisco, CA",
    github_url: "https://github.com/alexj",
    linkedin_url: "https://linkedin.com/in/alexjohnson",
    portfolio_url: "https://alexjohnson.dev",
  },
  {
    id: "solver-2",
    email: "priya.patel@university.edu",
    name: "Priya Patel",
    role: "student",
    avatarUrl: "https://i.pravatar.cc/150?u=solver2",
    university: "MIT",
    major: "Electrical Engineering & Computer Science",
    graduation_year: "2023",
    experience_level: "advanced",
    skills: ["Python", "Machine Learning", "Data Analysis", "TensorFlow", "PyTorch"],
    bio: "Machine learning enthusiast with experience in computer vision and NLP. I've completed internships at tech companies and contributed to open-source ML projects.",
    languages: ["English", "Hindi", "Gujarati"],
    areas_of_interest: ["AI/ML", "Computer Vision", "Natural Language Processing"],
    location: "Cambridge, MA",
    github_url: "https://github.com/priyap",
    linkedin_url: "https://linkedin.com/in/priyapatel",
  },
  {
    id: "solver-3",
    email: "marcus.williams@university.edu",
    name: "Marcus Williams",
    role: "student",
    avatarUrl: "https://i.pravatar.cc/150?u=solver3",
    university: "UC Berkeley",
    major: "Business Administration & Computer Science",
    graduation_year: "2025",
    experience_level: "beginner",
    skills: ["UI/UX Design", "Figma", "HTML/CSS", "JavaScript"],
    bio: "Studying business and CS with a focus on product design. I'm passionate about creating intuitive and beautiful interfaces that solve real problems.",
    languages: ["English"],
    areas_of_interest: ["Product Design", "Entrepreneurship", "Web Development"],
    location: "Berkeley, CA",
    github_url: "https://github.com/marcusw",
    linkedin_url: "https://linkedin.com/in/marcuswilliams",
    portfolio_url: "https://marcuswilliams.design",
  },
  {
    id: "solver-4",
    email: "sofia.rodriguez@university.edu",
    name: "Sofia Rodriguez",
    role: "student",
    avatarUrl: "https://i.pravatar.cc/150?u=solver4",
    university: "Georgia Tech",
    major: "Computer Engineering",
    graduation_year: "2024",
    experience_level: "intermediate",
    skills: ["Embedded Systems", "C++", "IoT", "PCB Design", "Arduino"],
    bio: "Computer engineering student specializing in IoT and embedded systems. I enjoy building hardware projects and programming microcontrollers.",
    languages: ["English", "Spanish"],
    areas_of_interest: ["IoT", "Robotics", "Smart Home Technology"],
    location: "Atlanta, GA",
    github_url: "https://github.com/sofiar",
    linkedin_url: "https://linkedin.com/in/sofiarodriguez",
  },
  {
    id: "solver-5",
    email: "james.kim@university.edu",
    name: "James Kim",
    role: "student",
    avatarUrl: "https://i.pravatar.cc/150?u=solver5",
    university: "University of Washington",
    major: "Data Science",
    graduation_year: "2023",
    experience_level: "advanced",
    skills: ["Data Analysis", "Python", "R", "SQL", "Tableau", "Power BI"],
    bio: "Data science student with strong analytical skills. I've worked on several projects involving large datasets and complex statistical analysis.",
    languages: ["English", "Korean"],
    areas_of_interest: ["Data Visualization", "Business Intelligence", "Big Data"],
    location: "Seattle, WA",
    github_url: "https://github.com/jamesk",
    linkedin_url: "https://linkedin.com/in/jameskim",
  },
  {
    id: "solver-6",
    email: "zoe.chen@university.edu",
    name: "Zoe Chen",
    role: "student",
    avatarUrl: "https://i.pravatar.cc/150?u=solver6",
    university: "Carnegie Mellon University",
    major: "Human-Computer Interaction",
    graduation_year: "2024",
    experience_level: "intermediate",
    skills: ["UX Research", "User Testing", "Wireframing", "Prototyping", "Figma"],
    bio: "HCI student focused on creating intuitive user experiences. I believe in user-centered design and validating assumptions through research and testing.",
    languages: ["English", "Mandarin"],
    areas_of_interest: ["UX Design", "Accessibility", "Mobile App Design"],
    location: "Pittsburgh, PA",
    github_url: "https://github.com/zoec",
    linkedin_url: "https://linkedin.com/in/zoechen",
    portfolio_url: "https://zoechen.design",
  },
  {
    id: "solver-7",
    email: "david.nguyen@university.edu",
    name: "David Nguyen",
    role: "student",
    avatarUrl: "https://i.pravatar.cc/150?u=solver7",
    university: "UCLA",
    major: "Computer Science",
    graduation_year: "2025",
    experience_level: "intermediate",
    skills: ["React Native", "Mobile Development", "JavaScript", "Firebase"],
    bio: "CS student specializing in mobile app development. I've created several apps available on the App Store and Google Play.",
    languages: ["English", "Vietnamese"],
    areas_of_interest: ["Mobile App Development", "Cross-platform Solutions", "UX Design"],
    location: "Los Angeles, CA",
    github_url: "https://github.com/davidn",
    linkedin_url: "https://linkedin.com/in/davidnguyen",
    portfolio_url: "https://davidnguyen.dev",
  },
  {
    id: "solver-8",
    email: "olivia.smith@university.edu",
    name: "Olivia Smith",
    role: "student",
    avatarUrl: "https://i.pravatar.cc/150?u=solver8",
    university: "NYU",
    major: "Interactive Media Arts",
    graduation_year: "2023",
    experience_level: "beginner",
    skills: ["UI Design", "Motion Graphics", "Adobe Creative Suite", "HTML/CSS"],
    bio: "Studying interactive media with a focus on digital experiences. I'm passionate about blending technology and art to create engaging user interfaces.",
    languages: ["English"],
    areas_of_interest: ["Interactive Design", "Motion UI", "Web Animation"],
    location: "New York, NY",
    github_url: "https://github.com/olivias",
    linkedin_url: "https://linkedin.com/in/oliviasmith",
    portfolio_url: "https://oliviasmith.design",
  },
  {
    id: "solver-9",
    email: "ethan.davis@university.edu",
    name: "Ethan Davis",
    role: "student",
    avatarUrl: "https://i.pravatar.cc/150?u=solver9",
    university: "University of Texas at Austin",
    major: "Computer Science",
    graduation_year: "2024",
    experience_level: "intermediate",
    skills: ["Golang", "Rust", "System Design", "Microservices", "Docker"],
    bio: "CS student focused on backend development and systems programming. I enjoy building efficient and scalable services.",
    languages: ["English"],
    areas_of_interest: ["Backend Development", "Distributed Systems", "Cloud Computing"],
    location: "Austin, TX",
    github_url: "https://github.com/ethand",
    linkedin_url: "https://linkedin.com/in/ethandavis",
  },
  {
    id: "solver-10",
    email: "maya.patel@university.edu",
    name: "Maya Patel",
    role: "student",
    avatarUrl: "https://i.pravatar.cc/150?u=solver10",
    university: "Brown University",
    major: "Applied Mathematics & Computer Science",
    graduation_year: "2023",
    experience_level: "advanced",
    skills: ["Algorithm Design", "Competitive Programming", "Python", "C++"],
    bio: "I'm passionate about solving complex algorithmic problems. I've participated in multiple programming competitions and hackathons.",
    languages: ["English", "Gujarati"],
    areas_of_interest: ["Algorithms", "Competitive Programming", "Software Engineering"],
    location: "Providence, RI",
    github_url: "https://github.com/mayap",
    linkedin_url: "https://linkedin.com/in/mayapatel",
  }
];

// Let's add some mock problems
export const mockProblems: Problem[] = [
  {
    id: "problem-1",
    title: "Build a React Native Mobile App",
    description: "We need a skilled developer to build a cross-platform mobile application for our startup.",
    startup_id: "1",
    required_skills: ["React Native", "JavaScript", "Mobile Development"],
    experience_level: "intermediate",
    compensation: "$2000-$3000",
    additional_info: "This is a 4-6 week project with potential for ongoing work.",
    status: "open",
    featured: true,
    applications_count: 5
  },
  {
    id: "problem-2",
    title: "Design a New Product Landing Page",
    description: "Looking for a UI/UX designer to create a compelling landing page for our new SaaS product.",
    startup_id: "2",
    required_skills: ["UI/UX Design", "Figma", "Web Design"],
    experience_level: "beginner",
    compensation: "$500-$1000",
    additional_info: "Should be completed within 2 weeks.",
    status: "open",
    featured: false,
    applications_count: 3
  },
  {
    id: "problem-3",
    title: "Implement Machine Learning Model",
    description: "We need help implementing a recommendation algorithm for our e-commerce platform.",
    startup_id: "3",
    required_skills: ["Python", "Machine Learning", "Data Science"],
    experience_level: "advanced",
    compensation: "$3000-$4000",
    additional_info: "This is a challenging project requiring strong ML skills.",
    status: "open",
    featured: true,
    applications_count: 2
  }
];

export default { mockSolvers, mockProblems };
